import type { Metadata } from "next";
import { Inter, Syne } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Landing/Footer/Footer";
import Navbar from "@/components/Navbar";

// const inter = Inter({ subsets: ["latin"] });

const inter = Syne({
  weight: ["400","500","600","700","800"],
  subsets:["latin-ext"]}
)

export const metadata: Metadata = {
  title: "Loreon Technologies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
