import localFont from 'next/font/local'
import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Landing/Footer/Footer";



import {  Arimo, Inter, Poppins, Roboto, Syne } from "next/font/google"
import Navbar from '@/components/Navbar';

export const RobotoFonts = Roboto({
    weight: ["100","300","400","700","900"],
    subsets:['latin'],
    variable: "--font-roboto"
})
  
  export const Pop = Poppins({
    weight: ["400","500","600","700","800"],
    subsets:["latin-ext"]}
  )
  
  export const InterFonts = Inter({
    weight: ["400","500","600","700","800"],
    subsets:["latin"]}
  )
  
export const Coolvetica = localFont({
  src: './fonts/coolvetica rg.ttf',
  display: 'swap',
  variable: '--font-coolvetica'
})


export const metadata: Metadata = {
  title: "Loreon Technologies",
  description: "Generated by create next app",

  openGraph:{
    title: "Generated by create next app",
    
  }
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" 
      className = {`${Coolvetica.variable} ${RobotoFonts.variable}`}>
      <body>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
